BlackJack/Controllers/GameLogicController.cs
using BlackJack.BLL.Interfaces;
using BlackJack.BLL.Services;
using BlackJack.DAL.Entities;
using BlackJack.VML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BlackJack.Controllers
{
    public class GameLogicController : Controller
    {
        GameLogicService _gameLogic;
        IRepository<Card> _cardRepository;
        public GameLogicController()
        {
            //_gameLogic = new GameLogicService(_cardRepository);
            _gameLogic = new GameLogicService();
        }


        [HttpGet]
        //public async Task<JsonResult> HandOverCards()
        public async Task<ActionResult> HandOverCards()
        {
            List<PlayerViewModel> playersModelList = await _gameLogic.HandOverCards();
            return View(playersModelList);
            //return Json(playersModel, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public async Task<ActionResult> PlayAgain(string yesOrNo)
        {
            List<PlayerViewModel> playersModelList = await _gameLogic.PlayAgain(yesOrNo);
            return View(playersModelList);
        }

        public async Task<ActionResult> Winner()
        {
            List<PlayerViewModel> playersModelList = await _gameLogic.Winner();
            return View(playersModelList);
        }

        public async Task<ActionResult> RoundHistory()
        {
            List<PlayerViewModel> playersModelList = await _gameLogic.RoundHistory();
            return View(playersModelList);
        }
    }
}

BlackJack/Controllers/GameSetController.cs
using BlackJack.BLL.Interfaces;
using BlackJack.BLL.Services;
using BlackJack.VML;
using ExceptionLogger;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BlackJack.Controllers
{
    public class GameSetController :Controller
    {
        IGamePlay _gamePlay;
        GameSetService _gameSetService;
        public GameSetController()
        {
            _gameSetService = new GameSetService();
        }

        public GameSetController(IGamePlay gamePlay)
        {
            _gamePlay = gamePlay;
        }


        public async Task<ActionResult> SetDeck()
        {
            await _gameSetService.SetDeck();
            List<CardViewModel> cards = await _gameSetService.GetDeck();
            return View(cards);
        }


        //public async Task<ActionResult> ReSetDeck()
        //{
        //    await _gameSetService.ReSetDeck();
        //    List<PlayingCardViewModel> cards = await _gameSetService.GetDeck();
        //    return View("SetDeck", cards);
        //}


        [ExceptionLogger]
        public async Task<ActionResult> SetBotCount()
        {
            try
            {
                await _gameSetService.InitializePlayers();
                await _gameSetService.SetBotCount(3);
            }
            catch (Exception ex)
            {
                return View("Error", new string[] { ex.Message });
            }
            return View();
        }


        public async Task<ActionResult> ShowPlayers()
        {
            List<PlayerViewModel> players = await _gameSetService.GetPlayers();

            return View(players);
        }


        public async Task<ActionResult> StartNewGame()
        {
            await _gameSetService.StartNewGame();
            List<CardViewModel> cards = await _gameSetService.GetDeck();
            return View("SetDeck", cards);
        }
    }
}

BlackJack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("StartNewGame", "StartNewGame", "GameSet", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("SetDeck", "SetDeck", "GameSet")</li>
                    <li>@Html.ActionLink("SetBotCount", "SetBotCount", "GameSet")</li>
                    <li>@Html.ActionLink("ShowPlayers", "ShowPlayers", "GameSet")</li>
                    <li>@Html.ActionLink("HandOverCards", "HandOverCards", "GameLogic")</li>
                    <li>@Html.ActionLink("Winner", "Winner", "GameLogic")</li>
                    <li>@Html.ActionLink("RoundHistory", "RoundHistory", "GameLogic")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>